name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd domains/memocracy.eu/public_html/admin/headless-cms/
            ./bin/deploy.sh
